apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-order
  labels:
    app: demo-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-order
  template:
    metadata:
      labels:
        app: demo-order
    spec:
      containers:
      - name: demo-order
        image: nexweb1/demo-zipkin-order:0.4
        ports:
        - containerPort: 8081
        env:
        - name: ZIPKIN_HOST
          value: zipkin
        - name: ZIPKIN_PORT
          value: "9411"